project/models.py
import datetime
from project import db, bcrypt
from flask_login import UserMixin

# SongTag = db.Table('songs_tags',
#                     db.Column('id',
#                                db.Integer,
#                                primary_key=True),
#                     db.Column('song_id',
#                               db.Integer,
#                               db.ForeignKey('songs.id',
#                               ondelete='cascade')),
#                     db.Column('tag_id',
#                               db.Integer,
#                               db.ForeignKey('tags.id',
#                               ondelete='cascade')),
#                    )

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Text, unique=True)
    email = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)
    first_name = db.Column(db.Text)
    last_name = db.Column(db.Text)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    songs = db.relationship('Song', backref='user', lazy='dynamic')

    # Future update: email verification
    # confirmed = db.Column(db.Boolean, nullable=False, default=False)
    # confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, username, email, password, first_name, last_name, admin=False):
        self.username = username
        self.email = email
        self.password = bcrypt.generate_password_hash(password).decode('UTF-8')
        self.first_name = first_name
        self.last_name = last_name
        self.registered_on = datetime.datetime.now()
        self.admin = admin

        # Future update: email verification
        # self.confirmed = confirmed
        # self.confirmed_on = confirmed_on


class Song(db.Model):
    __tablename__ = 'songs'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    artist = db.Column(db.Text)
    song_link = db.Column(db.Text)
    date_added = db.Column(db.DateTime, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    # tags = db.relationship('Tag',
    #                        secondary=SongTag,
    #                        backref=db.backref('tags', lazy='dynamic'))

    def __init__(self, title, artist, song_link, user_id):
        self.title = title
        self.artist = artist
        self.song_link = song_link
        self.date_added = datetime.datetime.now()
        self.user_id = user_id


# class Tag(db.Model):
#     __tablename__ = 'tags'
#
#     id = db.Column(db.Integer, primary_key=True)
#     tag = db.Column(db.Text)

project/songs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired

class SongForm(FlaskForm):
    title = StringField('Song Title', [InputRequired()])
    artist = StringField('Artist Name', [InputRequired()])
    # secondary_artist = StringField('Secondary Artist (optional)')
    song_link = StringField('Song Link', [InputRequired()])
    # tags = StringField('Song Tags', [InputRequired()])

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import InputRequired, Length, Email, EqualTo

class UserForm(FlaskForm):
    username = StringField('Username', [Length(min=4, max=12), InputRequired()])
    email = StringField('Email', [Email(), InputRequired()])
    password = PasswordField('Password', [Length(min=6, max=16), InputRequired(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Confirm Password', [Length(min=6, max=16)])
    first_name = StringField('First Name', [InputRequired()])
    last_name = StringField('Last Name', [InputRequired()])

class LoginForm(FlaskForm):
    username = StringField('Username', [InputRequired()])
    password = PasswordField('Password', [Length(min=6)])

project/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
import os

app = Flask(__name__)
app.config['SQALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')

if os.environ.get('ENV') == 'production':
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL')
else:
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/freedomsongs-db'

modus = Modus(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
db = SQLAlchemy(app)

from project.users.views import users_blueprint
from project.songs.views import songs_blueprint
from project.models import User, Song

app.register_blueprint(users_blueprint, url_prefix='/users')
app.register_blueprint(songs_blueprint, url_prefix='/users/<int:id>/songs')

@app.route('/')
def home():
    songs = Song.query.order_by("date_added asc").limit(10).all()
    return render_template('home.html', songs=songs)

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

project/songs/views.py
from project import db
from flask import render_template, redirect, request, url_for, Blueprint, flash
from project.songs.forms import SongForm
from project.models import Song
from project.users.views import ensure_correct_user
from flask_login import current_user, login_required

songs_blueprint = Blueprint(
    'songs',
    __name__,
    template_folder='templates'
)

@songs_blueprint.route('/', methods=['POST'])
def index(id):
    if current_user.get_id() == str(id):
        form = SongForm()
        if form.validate():
            new_song = Song(
                title = form.title.data,
                artist = form.artist.data,
                song_link = form.song_link.data,
                # tags = form.tags.data,
                user_id = id
            )
            db.session.add(new_song)
            db.session.commit()
            flash({'text': 'Thank you for contributing to the project. Your song was added to our database successfully!', 'status': 'success'})
            return redirect(url_for('home'))
    return render_template('songs/new.html', form=form)

@songs_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(id):
    form = SongForm()
    return render_template('songs/new.html', form=form, user_id=id)

@songs_blueprint.route('/<int:song_id>', methods =['GET', 'DELETE'])
def show(id, song_id):
  found_song = Song.query.get(song_id)
  if request.method == b"DELETE" and current_user.get_id() == id:
    db.session.delete(found_song)
    db.session.commit()
    return redirect(url_for('songs.index', id=id))
  return render_template('songs/show.html', song=found_song)

project/users/views.py
from project import db, bcrypt
from flask import render_template, redirect, request, url_for, Blueprint, flash
from project.users.forms import UserForm, LoginForm
from project.models import User
from flask_login import login_user, logout_user, current_user, login_required
from sqlalchemy.exc import IntegrityError
from functools import wraps

users_blueprint = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)

def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('id') != current_user.id:
            flash({'text': "Not Authorized", 'status': 'danger'})
            return redirect(url_for('home'))
        return fn(*args, **kwargs)
    return wrapper

@users_blueprint.route('/about')
def about():
    return render_template('users/about.html')

@users_blueprint.route('/faq')
def faq():
    return render_template('users/faq.html')

@users_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserForm()
    if request.method == 'POST':
        if form.validate():
            try:
                new_user = User(
                    username=form.username.data,
                    email=form.username.data,
                    password=form.password.data,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data
                )
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
            except IntegrityError as e:
                flash({'text': "Username already taken", 'status': 'danger'})
                return render_template('users/signup.html', form=form)
            return redirect(url_for('home'))
    return render_template('users/signup.html', form=form)

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        if form.validate():
            found_user = User.query.filter_by(username=form.username.data).first()
            if found_user:
                is_authenticated = bcrypt.check_password_hash(found_user.password, form.password.data)
                if is_authenticated:
                    login_user(found_user)
                    flash({'text': 'Welcome, {}!'.format(found_user.first_name), 'status': 'success'})
                    return redirect(url_for('home'))
            flash({'text': "Invalid credentials.", 'status': 'danger'})
            return render_template('users/login.html', form=form)
    return render_template('users/login.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash({ 'text': "You have successfully logged out.", 'status': 'success' })
    return redirect(url_for('users.login'))

@users_blueprint.route('/<int:id>/account', methods=['GET', 'PATCH', 'DELETE'])
@login_required
@ensure_correct_user
def account(id):
    user = User.query.get(id)
    form = UserForm()
    return render_template('users/account.html', form=form, user=user)

@users_blueprint.route('/<int:id>', methods=["GET", "PATCH", "DELETE"])
@login_required
def show(id):
  found_user = User.query.get(id)
  if request.method == 'GET' or current_user.is_anonymous or current_user.get_id() != str(id):
    return render_template('users/show.html', user=found_user)
  if request.method == b"PATCH":
    form = UserForm(request.form)
    if form.validate():
      if bcrypt.check_password_hash(found_user.password, form.password.data):
        found_user.username = form.username.data
        found_user.email = form.email.data
        db.session.add(found_user)
        db.session.commit()
        return redirect(url_for('users.show', id=id))
      flash({ 'text': "Wrong password, please try again.", 'status': 'danger'})
    return render_template('users/edit.html', form=form, user=found_user)
  if request.method == b"DELETE":
    db.session.delete(found_user)
    db.session.commit()
    return redirect(url_for('users.signup'))

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="{{url_for('static', filename='style.css')}}" rel="stylesheet" media="screen">
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"
   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
   crossorigin="anonymous"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
  {% block css %}{% endblock %}
  <title>Freedom Songs Project</title>
</head>
<body>
  {% include 'navigation.html' %}

  <br>

  {% for message in get_flashed_messages() %}
      <div class="alert alert-{{ message['status'] }}">{{ message['text'] }}</div>
    {% endfor %}

  {% block content %}
  {% endblock %}

</body>
</html>

project/templates/home.html
{% extends 'base.html' %}
{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1>Freedom Songs Project</h1>
      <p><i>Beyond pop privilege. Community curated database of songs of the movement by popular artists of color.</i>
      </p>
      <p><a class="btn btn-primary btn-lg" href="{{url_for('users.about')}}" role="button">Learn more</a></p>
    </div>
  </div>

{% for song in songs %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <h3>{{ song.title.title() }}</h3>
        <div class="embed-responsive embed-responsive-4by3">
          <iframe class="embed-responsive-item" src="{{ song.song_link }}" frameborder="0"></iframe>
        </div>
        <div class="well well-sm">
          <p id="tags"># tags</p>
        </div>
      </div>

{% endfor %}
    </div>
  </div>

{% endblock %}

project/templates/navigation.html
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{url_for('home')}}">Freedom Songs</a>
    </div>

      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search for a song">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
       {% if current_user.is_anonymous %}
         <li><a id="signup-btn" href="{{url_for('users.signup')}}">Sign Up</a></li>
         <li><a id="signup-btn" href="{{url_for('users.login')}}">Login</a></li>
       {% else %}
       <li><a id="signup-btn" href="{{url_for('songs.new', id=current_user.id)}}">Submit Song</a></li>
        <li><a id="signup-btn" href="{{url_for('users.logout')}}">Logout</a></li>
       {% endif %}
        <li class="dropdown">
          <a href="#" id="menu" class="dropdown-toggle glyphicon glyphicon-menu-hamburger" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
          <ul class="dropdown-menu">
            <li><a href="{{url_for('users.about')}}">About</a></li>
            <li><a href="{{url_for('users.faq')}}">FAQ</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>